spring.application.name=servico-auditor-dlq

spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
spring.cloud.aws.region.static=us-east-1

queue.dlq-name=T02N_LEONARDO_CHERINI-DLQ

spring.datasource.url=jdbc:h2:mem:auditordb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.io.awspring.cloud.sqs=INFO
logging.level.com.example.auditor=DEBUG
